# Generated by Django 5.1.2 on 2024-10-18 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0002_machinedata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='type',
        ),
    ]
