# Generated by Django 5.1.2 on 2024-10-19 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0005_alter_machinedata_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cncmachine',
            name='machine_ptr',
        ),
        migrations.RemoveField(
            model_name='leaktestmachine',
            name='machine_ptr',
        ),
        migrations.RemoveField(
            model_name='paintingrobot',
            name='machine_ptr',
        ),
        migrations.RemoveField(
            model_name='stampingpress',
            name='machine_ptr',
        ),
        migrations.RemoveField(
            model_name='weldingrobot',
            name='machine_ptr',
        ),
        migrations.DeleteModel(
            name='AGV',
        ),
        migrations.DeleteModel(
            name='CNCMachine',
        ),
        migrations.DeleteModel(
            name='LeakTestMachine',
        ),
        migrations.DeleteModel(
            name='PaintingRobot',
        ),
        migrations.DeleteModel(
            name='StampingPress',
        ),
        migrations.DeleteModel(
            name='WeldingRobot',
        ),
    ]
