# Generated by Django 5.1.2 on 2024-10-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0009_alter_machine_machine_type_delete_machinetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='machine_type',
            field=models.IntegerField(choices=[('Welding Robot', 'WELDING_ROBOT'), ('Stamping Press', 'STAMPING_PRESS'), ('Painting Robot', 'PAINTING_ROBOT'), ('Leak Test Machine', 'LEAK_TEST_MACHINE'), ('CNC Milling', 'CNC_MILLING'), ('AGV', 'AGV')]),
        ),
    ]
