# Generated by Django 5.1.2 on 2024-10-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0010_alter_machine_machine_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='machine_type',
            field=models.CharField(choices=[('Welding Robot', 'WELDING_ROBOT'), ('Stamping Press', 'STAMPING_PRESS'), ('Painting Robot', 'PAINTING_ROBOT'), ('Leak Test Machine', 'LEAK_TEST_MACHINE'), ('CNC Milling', 'CNC_MILLING'), ('AGV', 'AGV')], default='Welding Robot', max_length=50),
        ),
    ]
